/*
CCH World Factory - GPL

Copyright (C) 2014 Christopher Collin Hall
email: explosivegnome@yahoo.com

CCH World Factory - GPL is distributed under the GNU General Public 
License (GPL) version 3. A non-GPL branch of the CCH World Factory 
also exists. For non-GPL licensing options, contact the copyright 
holder, Christopher Collin Hall (explosivegnome@yahoo.com). 

CCH World Factory - GPL is free software: you can redistribute it 
and/or modify it under the terms of the GNU General Public License 
as published by the Free Software Foundation, either version 3 of 
the License, or (at your option) any later version.

CCH World Factory - GPL is distributed in the hope that it will be 
useful, but WITHOUT ANY WARRANTY; without even the implied warranty 
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with CCH World Factory - GPL.  If not, see 
<http://www.gnu.org/licenses/>.

*/
/*
 * Copyright 2014 - Christopher Collin Hall ( explosivegnome@yahoo.com )
 * All rights reserved.
 */
package hall.collin.christopher.worldgeneration.math;

import java.util.Random;

/**
 * This class is a simple implementation of AbstractNumberGenerator using 
 * <code>java.util.Random</code> as the number generator.
 * @author Christopher Collin Hall
 */
public class DefaultRandomNumberGenerator extends AbstractNumberGenerator {
	final Random prng;
	/**
	 * Instantiates with the given seed for the underlying number generator 
	 * (java.util.Random)
	 * @param seed A number to seed the generator 
	 */
	public DefaultRandomNumberGenerator(long seed){
		prng = new Random(seed);
	}
	/**
	 * Instantiates with the default seed for the underlying number generator 
	 * (java.util.Random)
	 */
	public DefaultRandomNumberGenerator(){
		prng = new Random();
	}
	/**
	 * Generates a number between 0 and 1. 
	 * If not overridden by the extending class, the default implementation is 
	 * as follows:<br/><code>
	 * return (double)(nextLong() & 0x000fffffffffffffL)/((double)0x000fffffffffffffL);
	 * </code>
	 * @return A number between 0 and 1.
	 */
	@Override
	public double nextDouble(){
		return prng.nextDouble();
	}
	/**
	 * Generates a number between 0 and 1. 
	 * If not overridden by the extending class, the default implementation is 
	 * as follows:<br/><code>
	 * return (float)(nextInt() & 0x007fffff)/((float) 0x007fffff);
	 * </code>
	 * @return A number between 0 and 1.
	 */
	@Override
	public float nextFloat(){
		return prng.nextFloat();
	}
	/**
	 * Generates an integer whose range is unbound.
	 * If not overridden by the extending class, the default implementation is 
	 * as follows:<br/><code>
	 * return (int)nextLong();
	 * </code>
	 * @return An integer
	 */
	@Override
	public int nextInt(){
		return prng.nextInt();
	}
	/**
	 * Generates a long integer whose range is unbound. This method must be 
	 * overridden by the extending class.
	 * @return An integer
	 */
	@Override
	public long nextLong(){
		return prng.nextInt();
	}
	/**
	 * Returns true or false.
	 * If not overridden by the extending class, the default implementation is 
	 * as follows:<br/><code>
	 * return (nextInt() & 0x10) == 0;
	 * </code>
	 * @return true or false
	 */
	@Override
	public boolean nextBoolean(){
		return prng.nextBoolean();
	}
	/**
	 * Fills the given array with generated byte values.
	 * @param byteBuffer A byte array to be filled.
	 */
	@Override
	public void nextBytes(byte[] byteBuffer){
		prng.nextBytes(byteBuffer);
	}
	/**
	 * Generates a number between <code>min</code> and <code>max</code>.
	 * @param min minimum value that can be generated
	 * @param max maximum value that can be generated
	 * @return A number between <code>min</code> and <code>max</code>
	 */
	@Override
	public double nextDouble(double min, double max){
		return (max-min)*nextDouble()+min;
	}
	/**
	 * Generates a number between <code>min</code> and <code>max</code>.
	 * @param min minimum value that can be generated
	 * @param max maximum value that can be generated
	 * @return A number between <code>min</code> and <code>max</code>
	 */
	@Override
	public float nextFloat(float min, float max){
		return (max-min)*nextFloat()+min;
	}
	/**
	 * Generates a number between <code>0</code> (inclusive) and 
	 * <code>limit</code> (exclusive).
	 * @param limit Upper limit on generated integer
	 * @return A number between <code>0</code> (inclusive) and 
	 * <code>limit</code> (exclusive).
	 */
	@Override
	public int nextInt(int limit){
		return prng.nextInt(limit);
	}
}
